// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include "../registry/reflect_macros.hpp"
// Symbol registry for the ELF loader.
// Maps symbol names to runtime addresses so the loader can resolve
// external references in loaded shader modules.

#include <cstring>
#include <cstddef>
#include <cstdlib>
#include <cmath>
#include <new>

// GCC/Clang combined sin+cos (generated by -O2 when both sin and cos are used)
#if defined(__GNUC__) || defined(__clang__)
extern "C" void sincosf(float x, float* sinp, float* cosp);
#endif

// C++ ABI: thread-safe static local initialization guards.
// Needed by modules that use static locals (e.g. KSL_PARAMS_BEGIN).
// The Itanium ABI specifies __int64 (long long) guard variables.
namespace ksl { namespace detail {
    extern "C" int  __cxa_guard_acquire(long long*);
    extern "C" void __cxa_guard_release(long long*);
}}

namespace ksl {

class KSLSymbolTable {
public:
    static constexpr size_t MAX_SYMBOLS = 64;

    void Register(const char* name, void* addr) {
        if (count_ < MAX_SYMBOLS) {
            entries_[count_].name = name;
            entries_[count_].addr = addr;
            count_++;
        }
    }

    void* Resolve(const char* name) const {
        for (size_t i = 0; i < count_; i++) {
            if (std::strcmp(entries_[i].name, name) == 0)
                return entries_[i].addr;
        }
        return nullptr;
    }

    size_t Count() const { return count_; }

    // Register all symbols that KSL shader modules may reference.
    void RegisterAll() {
        RegisterMath();
        RegisterRuntime();
    }

    // Standard C math functions used by ksl:: inline math wrappers.
    void RegisterMath() {
        using F1 = float(*)(float);
        using F2 = float(*)(float, float);

        Register("sinf",    reinterpret_cast<void*>(static_cast<F1>(::sinf)));
        Register("cosf",    reinterpret_cast<void*>(static_cast<F1>(::cosf)));
        Register("tanf",    reinterpret_cast<void*>(static_cast<F1>(::tanf)));
        Register("asinf",   reinterpret_cast<void*>(static_cast<F1>(::asinf)));
        Register("acosf",   reinterpret_cast<void*>(static_cast<F1>(::acosf)));
        Register("atanf",   reinterpret_cast<void*>(static_cast<F1>(::atanf)));
        Register("atan2f",  reinterpret_cast<void*>(static_cast<F2>(::atan2f)));
        Register("sqrtf",   reinterpret_cast<void*>(static_cast<F1>(::sqrtf)));
        Register("powf",    reinterpret_cast<void*>(static_cast<F2>(::powf)));
        Register("expf",    reinterpret_cast<void*>(static_cast<F1>(::expf)));
        Register("logf",    reinterpret_cast<void*>(static_cast<F1>(::logf)));
        Register("log2f",   reinterpret_cast<void*>(static_cast<F1>(::log2f)));
        Register("fabsf",   reinterpret_cast<void*>(static_cast<F1>(::fabsf)));
        Register("floorf",  reinterpret_cast<void*>(static_cast<F1>(::floorf)));
        Register("ceilf",   reinterpret_cast<void*>(static_cast<F1>(::ceilf)));
        Register("roundf",  reinterpret_cast<void*>(static_cast<F1>(::roundf)));
        Register("truncf",  reinterpret_cast<void*>(static_cast<F1>(::truncf)));
        Register("fmodf",   reinterpret_cast<void*>(static_cast<F2>(::fmodf)));
        Register("fminf",   reinterpret_cast<void*>(static_cast<F2>(::fminf)));
        Register("fmaxf",   reinterpret_cast<void*>(static_cast<F2>(::fmaxf)));

#if defined(__GNUC__) || defined(__clang__)
        Register("sincosf", reinterpret_cast<void*>(&::sincosf));
#endif
    }

    // C/C++ runtime symbols needed by compiled shader modules.
    void RegisterRuntime() {
        Register("memcpy",  reinterpret_cast<void*>(&::memcpy));
        Register("memset",  reinterpret_cast<void*>(&::memset));
        Register("strcmp",   reinterpret_cast<void*>(&::strcmp));
        Register("strncpy", reinterpret_cast<void*>(&::strncpy));
        Register("malloc",  reinterpret_cast<void*>(&::malloc));
        Register("free",    reinterpret_cast<void*>(&::free));

        // C++ ABI: operator delete (compiler generates vtable destructor entries)
        // _ZdlPvm = operator delete(void*, size_t)
        Register("_ZdlPvm", reinterpret_cast<void*>(
            static_cast<void(*)(void*, size_t)>(::operator delete)));

        // C++ ABI: thread-safe static local init guards (used by KSL_PARAMS macros)
        Register("__cxa_guard_acquire", reinterpret_cast<void*>(&detail::__cxa_guard_acquire));
        Register("__cxa_guard_release", reinterpret_cast<void*>(&detail::__cxa_guard_release));
    }

private:
    struct Entry {
        const char* name;
        void* addr;

        KL_BEGIN_FIELDS(Entry)
            KL_FIELD(Entry, name, "Name", -128, 127),
            KL_FIELD(Entry, addr, "Addr", 0, 0)
        KL_END_FIELDS

        KL_BEGIN_METHODS(Entry)
            /* No reflected methods. */
        KL_END_METHODS

        KL_BEGIN_DESCRIBE(Entry)
            /* No reflected ctors. */
        KL_END_DESCRIBE(Entry)

    };
    Entry entries_[MAX_SYMBOLS]{};
    size_t count_ = 0;
};

} // namespace ksl
